### ISSUE TITLE
Key for capital letter C handled oddly

### ISSUE THREAD

**Issue by nepa** [dokufreaks/plugin-keyboard#15]
I used the following markup:

`<key>Strg</key> + <key>C</key>.`

I was expecting a combination of the Ctrl key and the letter C. Instead, I got the Ctrl key twice.

It seems like `<key>C</key>` is a magical combination to create a Ctrl key. To actually get a key entitled with the letter C, I have to use lower-case `<key>c</key>`. A lower-case c will create a key with an upper-case C.

I'm not sure whether this is a bug or a feature, but I would appreciate, if `<key>C</key>` would create a key entitled with a capital letter C rather then the Ctrl key.

**Comment by nepa** [comment]
I checked the code and can confirm that this is a feature. Single letters are used as shortcuts for special keys throughout all language files. Still, I do not consider this a good solution and would appreciate, if they would be removed. However, downward compatibility might make this impossible.

At least the documentation should be updated then and suggest always using lower-case letters to create regular alphabetical keys.

**Comment by LarsGit223** [comment]
Done.
The plugin page has been extended with the following description:

> Some keys like the letter C are short cuts which will be expanded to a translated key name. For example <key>ALT+C</key> will show the same result as if you entered <key>ALT+Ctrl</key>. If you want to suppress this behaviour then include the letter between two '. E.g. if you really want to show the letter C instead of Ctrl then write <key>ALT+'C'</key>.


So there is already a solution for the problem.

**Comment by nepa** [comment]
Thank you, @LarsGit223.

Still, writing `<key>'C'</key>` or `<key>c</key>` seems rather counterintuitive.

**Comment by LarsGit223** [comment]
True. But as you wrote changing anything in general would break backwards compatibility.
Now it's at least documented and so I think we can close this issue.

**Comment by nepa** [comment]
Today I encountered another problem related to the shortcuts defined in the language files.

This was the markup of my DokuWiki article:

`Drücken Sie die Taste <key>Druck</key> oder <key>Print</key> auf Ihrer Tastatur...`

The result is not as expected:

> Drücken Sie die Taste [Druck] oder [Druck] auf Ihrer Tastatur...

The keyword _Print_ is defined in the language file and will be replaced by _Druck_ even though, I explicitly want the key to be labeled [Print] here.

So I still think, this issue needs to be addressed! **Does DokuWiki support plug-in settings?** Maybe we can make this replace-mechanism optional. By default it is enabled, so we will not break downward compatibility. At the same time the feature can be disabled on fresh installs, so the plug-in will not mess up articles.

**Comment by LarsGit223** [comment]
This can also be solved by writing ```<key>'Print'</key>```.

A configuration option will change the setting globally for all pages. If you imagine a wiki with many users, some might want the short cuts/translations and some not. So a global setting is not the overall solution. I.m.h.o the actual method is simple and flexible.

**Comment by nepa** [comment]
Introducing a setting, new wiki installations can choose to have this feature enabled or disabled. Existing installations can have the feature enabled on default, so downward compatibility is not broken. I was not talking about a per-user setting.

**Comment by LarsGit223** [comment]
I still think that this is not really required but for your comfort I implemented an configuration option.

Check out the latest master branch of the keyboard plugin and if you activate the option ```disable_translation``` then the content of the ```<kbd>``` tag will be used without any modifications. This means:
- no translation
- no shortcuts
- no automatic capital first letter
