### ISSUE TITLE
Render key names including plus sign or minus sign

### ISSUE THREAD

**Issue by mforkel** [dokufreaks/plugin-keyboard#18]
Is there a way to render key names that include a `-` or `+`? I can't manage to render the keys  `Max/Min/+` and  `Select/°C/°F/-` of my desktop clock...

**Comment by LarsGit223** [comment]
Here are some examples, maybe that helps you:
```
<key>A</key><key>+</key>
<key>ALT-+</key>
<key>ALT+-</key>
```
I am not sure about what you exactly want to achieve? What key combination would you like to display and how would you like it to look/being rendered?

**Comment by mforkel** [comment]
I would like to display single keys, specifically `Select/°C/°F-` and `Max/Min/+`. I realized that I can double the trailing `-` as in `<key>Select/°C/°F/--</key>` to render the first key. But I have not found a solution for the second key with its trailing `+`.

**Comment by LarsGit223** [comment]
Is this an acceptable solution: ```<key>Max-Min-+</key>```? What shall ```Max``` and ```Min``` mean? That are no keyboard keys. The intention of the keyboard plugin is to highlight single keyboards keys and display them as a combination by adding a ```+``` between them.

**Comment by mforkel** [comment]
I'm trying to write a little manual for my fancy desktop clock/thermometer/... It has a key labeled `Max/Min/+`. Your solution would render the same as `<kbd>Max/Min/</kbd>+<kbd>+</kbd>`, i.e. a key combination. I guess what I'm hoping for is an escape character that will tell the plugin to interpret `+` (or `-`) as a regular characters.

**Comment by LarsGit223** [comment]
I implemented a general escape mechanism. Please update the keyboard plugin (even if there is no update message!). After the update ```<key>'Max/Min/+'</key>``` should do what you want.

Please test and give feedback.
