### ISSUE TITLE
Add option to disable automatic uppercasing

### ISSUE THREAD

**Issue by skymal4ik** [dokufreaks/plugin-keyboard#19]
Hello!

For some cases I need to specify in my wiki if keyboard shortcut is lower- or uppercase:

```
<kbd>Ctrl+A</kbd>
<kbd>Ctrl+a</kbd>
```
Currently plugin automatically converts all chars to the upper case. Could be great to have an option or workaround to  turn this off.

Thanks!

**Comment by Klap-in** [comment]
Is escaping performing the job? https://www.dokuwiki.org/plugin:keyboard#escape_mechanism

**Comment by lpaulsen93** [comment]
You can force lowercase letters like this ```<key>Ctrl+'a'</key>```. I do not see a need for a change, closing this.
