### ISSUE TITLE
Wrong style when used with Bootstrap style

### ISSUE THREAD

**Issue by philippemilink** [dokufreaks/plugin-keyboard#22]
Hello,

I'm using your plugin with a wiki using the Boostrap3 theme (https://www.dokuwiki.org/template:bootstrap3). I noticed keys are not rendered as expected within the Bootstrap3 theme (see how it sould look on https://getbootstrap.com/docs/3.4/css/#code-user-input).

This comes from the CSS class `.__keyboard` you add to the `<kbd>` HTML elements. Could you, please, add an option do disable adding this CSS class ? (or make it automatically when another theme as the default one is used...)

And thanks for maintaining this plugin !

**Comment by philippemilink** [comment]
My bad, this option already exists: go to the wiki settings, look for the setting `plugin»keyboard»css_class` and remove the content of the field to disable the CSS class.

**Comment by lpaulsen93** [comment]
@philippemilink Thanks, I added a remark to the plugin page to make this clearer for other users.
