### ISSUE TITLE
Update not recognized by extension manager due to date mismatch

### ISSUE THREAD

**Issue by mforkel** [dokufreaks/plugin-keyboard#5]
After an update of the plugin to version 2015-08-03 in the extension manager, the plugin is still flagged as an update candidate. The dates specified in plugin.info.txt and VERSION (2015-07-12) don't match the new version advertised in the extension manager (2015-08-03).

**Comment by LarsGit223** [comment]
Oooops...I am sorry for the inconvenience. Should be fixed now.
Best Regards, Lars

**Comment by mforkel** [comment]
No problem. Thanks for the quick response!
