### ISSUE TITLE
Add support for kbd elements

### ISSUE THREAD

**Issue by krichter722** [dokufreaks/plugin-keyboard#7]
Currently `kbd` elements aren't displayed as keyboard signs. This increases portability of dokuwiki markup because it's [an official XHTML element9(http://www.w3schools.com/tags/tag_kbd.asp), but `key` which has to be used isn't.

**Comment by LarsGit223** [comment]
Done. The plugin page https://www.dokuwiki.org/plugin:keyboard has been updated too.

**Comment by LarsGit223** [comment]
Any feedback? Can I close this issue?

**Comment by krichter722** [comment]
I don't know how to update the plugin if `dokuwiki` didn't figure out that there's an update available.

**Comment by LarsGit223** [comment]
Ooops, sorry. Forgot to update the version.
Is done now, please check.

**Comment by krichter722** [comment]
Works, thanks!
